name: Docker Image CI

on:
  push:
    tags:
      - '*'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: passadoreg/nodereddocker:${{  github.ref_name }}
      -
        name: Inspect
        run: |
          docker image inspect passadoreg/nodereddocker:${{  github.ref_name }}

      - name: Update Image Version in the related deployment.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'deployment/deployment.yml'
          propertyPath: 'containers.image'
          value: passadoreg/nodereddocker:${{  github.ref_name }}
          branch: master
          targetBranch: master
          commitChange: true
          message: 'Update Image Version to passadoreg/nodereddocker:${{  github.ref_name }}' 
